apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: py3data
        imagePullPolicy: Always
        image: natihd16/py3data:latest
        command: ["python3",  "test.py"]
      restartPolicy: Never
  backoffLimit: 0

